# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LK0hz-Q05i05pvGLo_-dmUU1Bg0sILbV
"""

import numpy as np
a = ([1,2,3],[1,2,3])
print(a)